### ISSUE TITLE
[Criar perfil] -> [BACKEND] - Criar estrutura de pastas do projeto

### ISSUE THREAD

**Issue by adrianolvti** [Joao-Bittencourt/adote-me.au#2]
**Pastas de estrutura do framework Spring Boot 2.7.5 Java 17** - MAVEN
 - Model
 - Controller
 - Service
 - Repository
 - Configuration
 
**Arquivos de configuração**
- Pom.xml
- Application.properties

**Dependências Utilizadas**
- Spring Web
- Spring Boot DevTools
- Lombok
- Spring Data JPA
- H2 Database
- Validation
![springAdoteMeAu](https://user-images.githubusercontent.com/62856181/197281667-b1056bd8-927c-4066-b0ca-ae13cd2dd76e.JPG)

**Comment by MarcioMengerS** [comment]
Iniciado projeto através do [Spring Initializr](https://start.spring.io/) conforme imagem acima já com arquivos pom.xml e o application.properties(H2DB) configurados. 

Obs.: Ainda não modificada estrutura de pastas padrão para estrutura acima.

**Comment by MarcioMengerS** [comment]
### Algumas observações importantes:

1. A classe principal (Main) está rodando normalmenteno no VSCode IDE.
3. Sugiro fazermos o backend separado do frontend.

**Comment by Joao-Bittencourt** [comment]
closed
